import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabaseAdmin';

// GET - List all unpolish purchases
export async function GET(request: Request) {
  try {
    const supabase = supabaseAdmin;
    const { searchParams } = new URL(request.url);
    const factoryId = searchParams.get('factoryId');
    const month = searchParams.get('month');
    const year = searchParams.get('year');

    let query = supabase
      .from('unpolish_purchases')
      .select(`
        *,
        factories (
          id,
          name
        ),
        unpolish_material_types (
          id,
          name
        )
      `)
      .order('purchase_date', { ascending: false });

    // Filter by factory if provided
    if (factoryId) {
      query = query.eq('factory_id', factoryId);
    }

    // Filter by month and year if provided
    if (month && year) {
      const monthNum = parseInt(month);
      const yearNum = parseInt(year);
      const startDate = `${yearNum}-${monthNum.toString().padStart(2, '0')}-01`;
      
      // Calculate last day of month
      const lastDay = new Date(yearNum, monthNum, 0).getDate();
      const endDate = `${yearNum}-${monthNum.toString().padStart(2, '0')}-${lastDay}`;
      
      query = query.gte('purchase_date', startDate).lte('purchase_date', endDate);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Error fetching unpolish purchases:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(data || []);
  } catch (error) {
    console.error('Unexpected error in GET /api/unpolish-purchases:', error);
    return NextResponse.json(
      { error: 'Failed to fetch unpolish purchases' },
      { status: 500 }
    );
  }
}

// POST - Create new unpolish purchase
export async function POST(request: Request) {
  try {
    const supabase = supabaseAdmin;
    const body = await request.json();
    
    const {
      purchase_date,
      factory_id,
      factory_name,
      material_type_id,
      material_name,
      slabs_count,
      sft,
      rate_per_sft,
      remarks = '',
      created_by = 'system'
    } = body;

    // Validate required fields
    if (!purchase_date || !factory_id || !material_type_id || !sft || !rate_per_sft) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Calculate total amount
    const total_amount = parseFloat(sft) * parseFloat(rate_per_sft);

    // Insert purchase record (purchase_number will be auto-generated by trigger)
    const { data: purchase, error: purchaseError } = await supabase
      .from('unpolish_purchases')
      .insert({
        purchase_date,
        factory_id,
        factory_name,
        material_type_id,
        material_name,
        slabs_count: parseInt(slabs_count) || 0,
        sft: parseFloat(sft),
        rate_per_sft: parseFloat(rate_per_sft),
        total_amount,
        remarks,
        created_by
      })
      .select()
      .single();

    if (purchaseError) {
      console.error('Error creating purchase:', purchaseError);
      return NextResponse.json(
        { error: purchaseError.message },
        { status: 500 }
      );
    }

    return NextResponse.json(purchase, { status: 201 });
  } catch (error) {
    console.error('Unexpected error in POST /api/unpolish-purchases:', error);
    return NextResponse.json(
      { error: 'Failed to create purchase' },
      { status: 500 }
    );
  }
}

// PUT - Update existing purchase
export async function PUT(request: Request) {
  try {
    const supabase = supabaseAdmin;
    const body = await request.json();
    
    const {
      id,
      purchase_date,
      factory_id,
      factory_name,
      material_type_id,
      material_name,
      slabs_count,
      sft,
      rate_per_sft,
      remarks
    } = body;

    if (!id) {
      return NextResponse.json(
        { error: 'Purchase ID is required' },
        { status: 400 }
      );
    }

    // Calculate total amount
    const total_amount = parseFloat(sft) * parseFloat(rate_per_sft);

    const { data: purchase, error } = await supabase
      .from('unpolish_purchases')
      .update({
        purchase_date,
        factory_id,
        factory_name,
        material_type_id,
        material_name,
        slabs_count: parseInt(slabs_count) || 0,
        sft: parseFloat(sft),
        rate_per_sft: parseFloat(rate_per_sft),
        total_amount,
        remarks
      })
      .eq('id', id)
      .select()
      .single();

    if (error) {
      console.error('Error updating purchase:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(purchase);
  } catch (error) {
    console.error('Unexpected error in PUT /api/unpolish-purchases:', error);
    return NextResponse.json(
      { error: 'Failed to update purchase' },
      { status: 500 }
    );
  }
}

// DELETE - Delete a purchase
export async function DELETE(request: Request) {
  try {
    const supabase = supabaseAdmin;
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json(
        { error: 'Purchase ID is required' },
        { status: 400 }
      );
    }

    const { error } = await supabase
      .from('unpolish_purchases')
      .delete()
      .eq('id', id);

    if (error) {
      console.error('Error deleting purchase:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Unexpected error in DELETE /api/unpolish-purchases:', error);
    return NextResponse.json(
      { error: 'Failed to delete purchase' },
      { status: 500 }
    );
  }
}
